### ISSUE TITLE
Chat Extension not working on Messenger web app?

### ISSUE THREAD

**Issue by amaurymartiny** [fbsamples/messenger-bot-samples#1]
Trying out the new chat extension TaskBot. When I edit a list on messenger.com web app, I get redirected to heroku with this message:
![screen shot 2017-04-18 at 10 06 21 pm](https://cloud.githubusercontent.com/assets/1293565/25151155/c68a42bc-2484-11e7-8742-17654e169f33.png)

Are chat extensions working in browsers?

**Comment by iboldurev** [comment]
@amaurymartiny 
Hi, messenger webview not support web browser.
Only messenger app. 😠

**Comment by schvenk** [comment]
From the [Chat Extensions FAQ](https://developers.facebook.com/docs/messenger-platform/guides/chat-extensions#faq) in the Messenger Platform developer docs:

> **Does Chat Extensions work on Messenger.com and Facebook.com?**
> This feature is supported on iOS and Android only. Users on web-based clients may be able to click links shared by Chat Extensions users, but will not be able to use the functionality provided by the JavaScript SDK. For more info, see "Backwards Compatibility" in the Chat Extensions Best Practices Guide.
