### ISSUE TITLE
gui-webview for those who are not familiar with Ract

### ISSUE THREAD

**Issue by a-fawzy** [fbsamples/messenger-bot-samples#12]
Please can you provide examples for developers who are not familiar with React techniques?
Simple DOM and CSS documentation to start with will be more than enough.

Or simply may you create another version of gui-webview which can run on PCs (instead of messenger only) so we could inspect DOMs and Classes on the browser and find our way through it?

**Comment by tcsapunaru** [comment]
Hi @a-fawzy, unfortunately this example is built on top of React and it's impossible to change.
We allow webviews only from within the app for the best UX. 

FWIW the enforcement of having the messenger extensions loaded starts somewhere around here --> you would be able to setup your own environment using the provided instructions and tweak it here to be able to load the view on a web browser if you want to do that.
