### ISSUE TITLE
chat extensions example is broken

### ISSUE THREAD

**Issue by omrihaviv** [fbsamples/messenger-bot-samples#15]
I ran the entire tutorial to set-up my own Tasks bot. 
When I click 'Create a List' on messenger the webview pops up and finishes loading but when it finishes all I see is a blank page.
I also tried from two iPhones with two different facebook accounts to use Facebook's Tasks bot and it also gives a blank page when clicking 'Create a List'.

I find it very difficult to debug the issue as I cannot click that url from a desktop browser, as it returns a message that this page is only supported on iOS or Android.

**Comment by depombo** [comment]
I am experiencing the same issue. To clarify, only the 'Create a List' button in the menu exhibits the issue. I am able to open the 'Create a List' webview from the messenger extension button.

**Comment by depombo** [comment]
https://developers.facebook.com/bugs/1676913532599603/

**Comment by tcsapunaru** [comment]
Are you still experiencing this? In order to debug it put a div inside the page and dump the exception there. Then test it on your mobile in the webview.

Did a test on my side and it works fine.

**Comment by tgrrr** [comment]
Same problem here with demo bot for group tasks:

![s70731-014008](https://user-images.githubusercontent.com/4689707/28754865-a15c418a-7591-11e7-94a3-373d802f8e9f.jpg)

Problem occurs when selecting 'create list'.
I dont have problems displaying other webviews

Messenger version 128.0.0.21.88 
Android

Cheers,

P

**Comment by tcsapunaru** [comment]
@tgrrr webviews are now available on desktop so it should be easier to debug. Can you look into what error is being thrown and post it here?

**Comment by ga-davis** [comment]
@tcsapunaru The browser seems to be rejecting the connection because it is http instead of https. I'll share the exact logs in a moment, does the server need to be created with the https package?

**Comment by ga-davis** [comment]
[Warning] [blocked] The page at https://{DOMAIN}/lists/new was not allowed to display insecure content from http://{DOMAIN}/socket.io/?EIO=3&transport=polling&t=LshGGa5. (bundle.js, line 23185)

[Error] XMLHttpRequest cannot load http://{DOMAIN}/socket.io/?EIO=3&transport=polling&t=LshGGa5 due to access control checks.
	create (bundle.js:23185)
	Request (bundle.js:23090)
	request (bundle.js:23017)
	doPoll (bundle.js:23047)
	poll (bundle.js:11074)
	doOpen (bundle.js:11019)
	open (bundle.js:7412)
	open (bundle.js:22181)
	Socket (bundle.js:22060)
	Socket (bundle.js:21970)
	connect (bundle.js:18197)
	(anonymous function) (bundle.js:18511)
[Warning] [blocked] The page at https://{DOMAIN}/lists/new was not allowed to display insecure content from http://{DOMAIN}/socket.io/?EIO=3&transport=polling&t=LshGHoL. (bundle.js, line 23185)

[Error] XMLHttpRequest cannot load http://{DOMAIN}/socket.io/?EIO=3&transport=polling&t=LshGHoL due to access control checks.
	create (bundle.js:23185)
	Request (bundle.js:23090)
	request (bundle.js:23017)
	doPoll (bundle.js:23047)
	poll (bundle.js:11074)
	doOpen (bundle.js:11019)
	open (bundle.js:7412)
	open (bundle.js:22181)
	Socket (bundle.js:22060)
	Socket (bundle.js:21970)
	connect (bundle.js:18197)
	(anonymous function) (bundle.js:18511)

**Comment by ga-davis** [comment]
Ok, the insecure content issue was just a problem with my local config but now I'm seeing this on Desktop and Mobile:

TypeError: undefined is not an object (evaluating 'window.MessengerExtensions.getGrantedPermissions')

**Comment by tcsapunaru** [comment]
Hi, that sounds familiar. We are aware of an issue which may cause this and are looking into it. I'll update here when it's fixed.

**Comment by tcsapunaru** [comment]
This went stale closing as issue disappeared in the meantime.

**Comment by tomasdev** [comment]
For those coming here when you're setting the `x-frame-options` to the proper allow domains, there's an open bug on FB side https://developers.facebook.com/bugs/147147746075305/

**Comment by albttx** [comment]
Still broken..
