### ISSUE TITLE
Heroku build showing Internal Server Error for Messenger Extension

### ISSUE THREAD

**Issue by sauravk6** [fbsamples/messenger-bot-samples#17]
I tried running the messenger extension following the github tutorial from their facebook's demo messenger extension https://github.com/fbsamples/messenger-bot-samples/tree/master/chat-extensions 

I did all the steps exactly as mentioned but when I am opening the heroku url, its showing me internal server error and the /webhook route of url is showing me wrong token. I am not able to figure out where I am going wrong. Any help is appreciated. Thanks!

![screen shot 2017-07-13 at 12 11 16 pm](https://user-images.githubusercontent.com/14097057/28153764-e72ce988-67c4-11e7-90af-4d00c570ca74.png)

**Comment by RohitBansal18** [comment]
Hi, is this issue resolved on your side ...or still need help?

**Comment by sauravk6** [comment]
yes, this issue is resolved. some configuration mistake. Closing this issue.
