### ISSUE TITLE
Please try in Messenger App

### ISSUE THREAD

**Issue by tk4d** [fbsamples/messenger-bot-samples#20]
I get 'Please try in messenger app' even if I am on the Messenger App. Regardless, with the new update to 2.1, shouldn't this work on anything (browser)? 
If I view Victoria Belle using latest Messenger app on iOS, 75% of the time the 'Gift Preferences menu button' webview won't load and I get the 'Please Try in Messenger App'. Maybe a bug or the code needs to be updated to reflect recent changes? The compact webview for view details seems to work.

**Comment by tcsapunaru** [comment]
Can you recheck @tk4d? I think it should be ok now.

**Comment by tk4d** [comment]
Yep, looks like that did it!
