### ISSUE TITLE
call MessengerExtensions.requestCloseBrowser function from js file?

### ISSUE THREAD

**Issue by anusha9213** [fbsamples/messenger-bot-samples#26]
I am using a simple node.js project without babel and other configurations.
 I have a feedback.js file in routes and feedform.ejs file.

I have added messenger extensions sdk in **feeback.ejs** file. In the following way :

    <script>
    		(function(d, s, id){
    			var js, fjs = d.getElementsByTagName(s)[0];
    			if (d.getElementById(id)) {return;}
    			js = d.createElement(s); js.id = id;
    			js.src = "//connect.facebook.com/en_US/messenger.Extensions.js";
    			fjs.parentNode.insertBefore(js, fjs);
    		}(document, 'script', 'Messenger'));
    
    		window.extAsyncInit = function() {
    			// the Messenger Extensions JS SDK is done loading 
    			var isSupported = MessengerExtensions.isInExtension(); 
    
    			MessengerExtensions.getContext('************', 
    				function success(result){
    				
    				document.getElementById("psidid").value = result.psid;
    				},
    				function error(result){
    				//alert("json str "+JSON.stringify(result));
    				}
    			)
    			
    		};
    
    	
    	</script>

I am able to retrieve the psid as well. In the feedback form in post action I am calling a function in a js file.

eg :  

    <form method="post" action="/feeback/submit">
    	
    	<table cellpadding="11">
    		
    		<tr>
    		<td class="label">First Name</td><td>: <input type="text" name="fname" required></td>
    		</tr>
    		<tr>
    		<td class="label">Last Name</td><td>: <input type="text" name="lname" required></td>
    		</tr>
    	</table>
    	</form>

In **app.js** file  :

    app.post('/feeback/submit', feedback.submit);

I am calling a function(  **submit** ) in feedback.js file:

In the function I am saving the form data to Database and I should be able to close the webview also on successfully saving the data.

How can I acheive it?

I used the below method but I am getting MessengerExtensions is not defined error :

    MessengerExtensions.requestCloseBrowser(function success() {
      	// webview closed
    	user.doDataResponse(psid, message);
    }, function error(err) {
      // an error occurred
    });

I tried calling using  window.MessengerExtensions.requestCloseBrowser but getting window is undefined error.

Please tell me how can i resolve the issue?

**Comment by DaniyalGeek** [comment]
Hello,

Did you solve this issue?

**Comment by embee8** [comment]
Hi guys. Please note that this issue log is specific to the Tasks demo project. While your project also uses the Extension SDK, it's not directly related to this repository.

Based on your error message, the SDK was not loaded on your submit page. You have to make sure to embed the SDK on every page on which you want to use the SDK functions, and then close the webview in the `extAsyncInit`function.

For more detailed questions and answers, please join https://www.facebook.com/groups/messengerplatform - a group for developers to ask any question about the Messenger Platform.
