### ISSUE TITLE
'Tried accessing nonexisting field (whitelisted_domains) on node type (Page)'

### ISSUE THREAD

**Issue by Kibetchirchir** [fbsamples/messenger-bot-samples#33]
`Failed calling Messenger API endpoint thread_settings 500 Internal Server Error { message: 2018-08-17T10:41:46.442834+00:00 app[web.1]: 'Tried accessing nonexisting field (whitelisted_domains) on node type (Page)',`

I am getting this error when i deploy my app to heroku

**Comment by embee8** [comment]
Since there are several projects in this repository, can you specify which one you are trying to deploy?

**Comment by Kibetchirchir** [comment]
I specified... I am deploying the GUI-webview

**Comment by Kibetchirchir** [comment]
(#100) The URL provided is not whitelisted for messenger extensions',


this is the error im getting now

someone please assist im stuck
