### ISSUE TITLE
Messenger App detected as Web (Again (Again))

### ISSUE THREAD

**Issue by eoinclancy1** [fbsamples/messenger-bot-samples#39]
Currently experiencing the same issue on iOS 12.2 on iPhone Xs. It keeps telling me to access the service via the native app, which is where I am

**Comment by embee8** [comment]
Can you specify what project of this repository you are testing and where? Besides that, I just migrated all projects to the latest Graph API version, which might resolve your issue.

**Comment by eoinclancy1** [comment]
Sure. Currently working on the chat-extension and running it from Heroku. Have tested it across a couple of android and iOS devices through the FB app and still running into the same issue

**Comment by embee8** [comment]
Have a look at https://github.com/fbsamples/messenger-bot-samples/blob/d6b2f8a8831f2939304018b409e2f37deaf7dc10/chat-extensions/views/index.ejs#L17 where the context is retrieved. If that call fails, the `viewerId` in the `attachApp` function will be undefined (see https://github.com/fbsamples/messenger-bot-samples/blob/master/chat-extensions/client/index.js#L32), resulting in the error message to show up. A possible cause is attempting to load a non-whitelisted domain.

I generalized the error message with 40ccbfab1f068f04dabfd2a3a08821197bce883e to make it clearer that it might not necessarily be a user agent issue when the extension fails to load.
