### ISSUE TITLE
Messenger drops beginShareflow (deprecates chat extensions?)

### ISSUE THREAD

**Issue by ullenius** [fbsamples/messenger-bot-samples#43]
Messenger is being updated as of 15 August 2019 and new versions of the app will drop support for:
* beginShareFlow()
* Share to Messenger SDK
* Share button (won't render)

Full [changelog](https://developers.facebook.com/docs/messenger-platform/changelog) 

Does this effectively render the Shopping List bot (chat extension example) unusable?

**Comment by embee8** [comment]
Thanks for flagging this! Not unusable but it makes sharing less smooth. We will have to rely on Messenger's native forward functionality instead. I was thinking of sending the forward message to the operating user and then prompt the user to share it from the thread. Will run some tests to figure out what the best option is.

**Comment by m4rkus** [comment]
+1. Looks like FB still are changing their API:s in a way that breaks current apps completely which makes it very risky to allocate budgets for developing for their infrastructure. Looking forward to see a solution to this. Is perhaps WhatsApp a better platform for doing these kinds of things without risking API:s suddenly are removed arbitrarily?

**Comment by ullenius** [comment]
@m4rkus Probably not since Facebook owns WhatsApp. 

From my understanding they are making the changes for privacy reasons (i.e. [Cambridge Analytica Scandal](https://en.wikipedia.org/wiki/Facebook%E2%80%93Cambridge_Analytica_data_scandal))

**Comment by m4rkus** [comment]
@ullenius I fail to see what is removed though, these changes should have been in effect since Aug 15, I am using Messenger built in September and all apps including Tasks still seem to be able to share content (?)

**Comment by ullenius** [comment]
@m4rkus if it's working for you then great. However it's still being listed as deprecated on their site:

> The following APIs are deprecated on v4.0+ and will be removed from all versions on October 29th, 2019

**Comment by m4rkus** [comment]
@ullenius According to https://developers.facebook.com/docs/messenger-platform/changelog/ 
- Location Quick Reply Button
- Messenger Share Button
- Messenger Codes API
Are deprecated and will be removed on Oct 29, but Share to Messenger SDK  / Begin share flow Messenger extension SDK should have been removed already by 15th Aug...

Still weird that this example that seem to be the official example (?) on how to use extensions is not updated to reflect the current API:s and bots from Facebook controlled companies like Zynga are depending on these API:s even after they should have been removed. Thank you @ullenius for highlighting this issue and big ups to @embee8 for trying to find a clean workaround :)

**Comment by embee8** [comment]
I am about to commit a workaround which makes the share flow look like this:
![New - gif short](https://user-images.githubusercontent.com/12213984/65999925-50014a80-e496-11e9-8f82-3aca3a1e5add.gif)
