### ISSUE TITLE
gui-WebView React script not running on Android 4.4

### ISSUE THREAD

**Issue by devlesedi** [fbsamples/messenger-bot-samples#5]
I ran the gui-webview example successfully. On messenger, the webview loaded the React app just fine on my Android 6.0 device while failing to render on my Android 4.4.
![screenshot_2017-04-20-22-52-43](https://cloud.githubusercontent.com/assets/7551308/25269746/42fc4188-267e-11e7-86a3-f6abcfcab61a.png)

**Comment by tcsapunaru** [comment]
@devlesedi maybe it's an API incompatibility. What is the error that's being thrown?

My personal preferred way to surface these out is overriding the console.log call and then outputting the error to a div, some pointers here --> http://stackoverflow.com/questions/6604192/showing-console-errors-and-alerts-in-a-div-inside-the-page

**Comment by devlesedi** [comment]
As I've been trying to smoke out the problem. I used `window.onerror` to send the logs to my server.
The server receives the following from the client (Android device).

`
PUT Log response: {"_csrf":"undefined","msg":"Uncaught ReferenceError: Map is not defined","url":"http://192.168.43.76:3000/bundle.js","line":"28","location":"http://192.168.43.76:3000/"}
`

I'm guessing my phone's browser doesn't support some of the EC6 features.

UserAgent string for my Android phone:
`Mozilla/5.0 (Linux; Android 4.4.4; SM-J110F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36`

**Comment by devlesedi** [comment]
Adding babel-polyfill fixed it.
