### ISSUE TITLE
Documentation for extensions

### ISSUE THREAD

**Issue by jeriscc** [fbsamples/messenger-bot-samples#8]
Hi,

I am a more or less new to the Facebook messenger platform and this project seems to be an advanced assembly of its features. I was wondering if would be possible that you folks create a more detailed documentation about how it works rather than just what technologies and libraries were utilized.

Thanks!

**Comment by schvenk** [comment]
We have some Getting Started guides, including some more introductory sample code, on our developer website: https://developers.facebook.com/docs/messenger-platform/getting-started
